### ISSUE TITLE
AM2 mob spawning

### ISSUE THREAD

**Issue by Divineaspect** [belathus/Wanderlust-Renewed#10]
AM2 has some amazing mobs, but they are mostly spawning with chunk creation / worldgen and not replenishing after that.

EnderZoo or CustomMobProperties to get them generating?

**Comment by belathus** [comment]
Looking at EnderZoo, we can do it pretty easily that way. It only gives the basic capabilities, such as biome restriction, dimension restriction, and rate. Combining it with MobProperties, though, could be pretty amazing.
