### ISSUE TITLE
Adding Marble to Alchemy Catalyst Rock Transmutation Loop

### ISSUE THREAD

**Issue by Alan19** [belathus/Wanderlust-Renewed#104]
Marble should be transmutable into andesite, granite and diorite

**Comment by belathus** [comment]
Are you suggesting we add a way to make marble via transmutation? I recall there being a way to make diorite, andesite, and granite by dropping stone into a mana pool with the alchemy catalyst.

**Comment by Alan19** [comment]
I meant allowing marble to be transmutable into andesite in the alchemy catalyst and diorite be transmutable into marble since the alchemy catalyst has a loop where you can transmute the stones into other stones
