### ISSUE TITLE
Living in the Nether and the Pure Daisy

### ISSUE THREAD

**Issue by belathus** [belathus/Wanderlust-Renewed#105]
Botania's Pure Daisy can be used to convert a ton of nether materials to their overworld equivalents. For example, it can convert netherrack to cobblestone and soulsand to sand. I'm thinking about adding more to this. For example, converting Natura's tainted dirt to dirt, heat sand to sand, PrimalCore's netherdirt to dirt, Cinisclay to clay, and so on. In addition, I'm considering methods of obtaining petals and water in the Nether so you can make a pure daisy.

Right now, I think you could get petals by bonemealing dirt and collecting the flowers, then turning the flowers into floral fertilizer. The problem is that you can't get dirt without an overworld trip before you have a pure daisy. Something I'm considering, though, is adding the pure daisy as loot in a nether fortress or adding a Recurrent Complex structure that specifically has either a pure daisy or dirt in it.

As for water: I like the idea of adding a recipe that allows you to fill a water bucket using valus melons.

@Divineaspect, what do you think?

**Comment by Divineaspect** [comment]
We could add the natura nether soils which I think can be used to create dirt, as well as have things planted on them.

As for  water, yes to 8 valus melons around a bucket making a water bucket, howabout also
8 snowballs around a bucket with a pure daisy recipe for ash into snow?

**Comment by belathus** [comment]
Not a bad idea for the ash. That'll be easy to implement. I don't think heat sand and tainted soil spawn right now, and there is no option to add it via the configs (unless "override nether chunk provider" does that). Both Natura and PrimalCore have an option to override the chunk provider, and currently both of them are disabled. PrimalCore's was disabled recently, though.

I can always add both heat sand and tainted soil via COG. I was thinking of having heat sand spawn under or beside lava, and have uranium and plutonium ore spawn under the heat sand.

**Comment by Divineaspect** [comment]
We should put the rftools dimensional shards down there as well, and disable it from spawning otherwise in the nether.

If we had the adjustable background BASE I'd also suggest redstone ores there.

**Comment by belathus** [comment]
Redstone, uranium, and dimensional shards now all generate below the lava, and RFTool's own oregen is disabled for the Nether. RFTools still handles shard oregen for the End.
