### ISSUE TITLE
More ways to make coal coke.

### ISSUE THREAD

**Issue by Lance5057** [belathus/Wanderlust-Renewed#108]
There should either be a way to convert the various types of coal into vanilla coal or a way to cook the other coal types into coke.

**Comment by belathus** [comment]
Anthracite to 2 coal coke. Is this what you had in mind?

**Comment by belathus** [comment]
Alright, anthracite makes 2 coal coke. Bituminous coal no longer spawns (I may make a bituminous coal coke at some point and re-enable it). Vanilla coal can make coke, and lignite can be upgraded to vanilla coal via the basic coal refiner. The only fuel you can find in the world added by this mod that you cannot make into coke is peat.
