### ISSUE TITLE
CAKE CAKE CAKE CAKE CAKE

### ISSUE THREAD

**Issue by TBone311xXx** [belathus/Wanderlust-Renewed#112]
You can't make lies without CAKE!

**Comment by TBone311xXx** [comment]
Wheat/Barley flour are uncraftable, Milk bottles are unobtainable

**Comment by belathus** [comment]
animania:freisian_bucket_milk and animania:holstein_bucket_milk should be able to be used to make cake. I'm a bit amused by how everything fit together to make cake uncraftable.

**Comment by belathus** [comment]
I see a recipe [in the brick oven](https://github.com/belathus/Wanderlust-Renewed/blob/master/config/betterbeginnings/BrickOven/main.json#L59-L98). Does that work?

It is basically:
MMM
SES
WWW

Where M is milk, S is sugar, E is egg, and W is wheat. You can get vanilla milk from crafting Animania cow milk in the crafting grid. Eggs from Animania chickens and their nests.

Can you tell me if this works?

**Comment by Divineaspect** [comment]
Brick oven recipe works for cake!
