### ISSUE TITLE
Ability totems should be convertable to a resource that can make Better ability totems

### ISSUE THREAD

**Issue by TBone311xXx** [belathus/Wanderlust-Renewed#115]

**Comment by belathus** [comment]
If I were to implement this, I'd have to make a new type of resource. I can create, say, an "enhanced gold" ingot via B.A.S.E.

I'm thinking you'd get an enhanced gold nugget from smelting an ability totem, then you craft together the nuggets to get an ingot. Then, you use the ingot to combine it with some other ingredients to make a different ability totem; IE, regen might use bottled hearts, or absorption uses golden hearts.

**Comment by Divineaspect** [comment]
Philosopher's Gold

Jeremiah Grimsley


"All of humanity is in peril of extinction if each one of us does not dare,
now and henceforth, always to tell only the truth, and all the truth, and
to do so promptly — right now." - R Buckminster Fuller

**Comment by belathus** [comment]
Philosopher's Gold can be made by smelting ability totems. Now I just need to add crafting recipes to turn it into another ability totem.

**Comment by Alan19** [comment]
Do you need any help with the rest of the ability totems?

**Comment by Alan19** [comment]
Opps
