### ISSUE TITLE
Thermal Expansion Fuels

### ISSUE THREAD

**Issue by belathus** [belathus/Wanderlust-Renewed#116]
Each of the reactant dynamo, magmatic dynamo, and compression dynamo can have fluids added to their fuel list. Available possible fuels include canola oil, empowered oil, crystallized oil, ethanol, biodiesel, hooch, fire water, hydrogen, rocket fuel, and syngas. We could also add fuels to the reactant dynamo like honey, poison, blood, or life essence. We even have antimatter as a possible choice. For a mostly up-to-date list of fluids, check [here](https://github.com/belathus/Wanderlust-Renewed/wiki/Liquid-List). Also, [this](https://github.com/belathus/Wanderlust-Renewed/blob/master/config/cofh/thermalexpansion/fuels.cfg) is the file I'd be editing.

I'll list the available fuels below:

#### Compression Dynamo
* **Coal**: 500,000. (liquifacted coal)
* **Fuel**: 2,000,000 (Buildcraft's fuel/gasoline)
* **Refined Oil**: 1,250,000 (no idea)
* **Tree Oil**: 1,000,000 (no idea)

#### Magmatic
* **Lava**: 180,000
* **Pyrotheum**: 2,000,000

#### Reactant Dynamo
* **aerotheum**: 1,250,000
* **biomass**: 450,000 (Forestry; not ethanol)
* **creosote**: 250,000 (Immersive Engineering)
* **glowstone**: 600,000 (energized glowstone)
* **mobessence**: 500,000 (MFR)
* **redstone**: 500,000 (destabilized redstone)
* **seedoil**: 250,000 (Forestry)
* **sewage**: 24,000 (MFR)
* **sludge**: 24,000 (MFR)

**Comment by Divineaspect** [comment]
I presume the refined oil is the result of their own system for refining oil
the tree oil is extracted as sap I think, and then refined.


Jeremiah Grimsley


"All of humanity is in peril of extinction if each one of us does not dare,
now and henceforth, always to tell only the truth, and all the truth, and
to do so promptly — right now." - R Buckminster Fuller

**Comment by belathus** [comment]
I just updated the list of liquids in the wiki. Looks like we now have an oil (Oil), a fuel (Refined Fuel), a tree oil (Tree Oil), and a refined oil (Naphtha). I'm guessing these were all added by Thermal Foundation. In any case, I can add more fuels to this list if we want. I see chloromethane as a fluid. That's new, and it is a highly flammable and toxic refrigerant.

**Comment by belathus** [comment]
Alright, I added a ton of fuels. We will almost assuredly have to balance the fuels as we discover which ones are easiest to obtain and/or work with. Also, if it makes more sense to dump a fluid on a different dynamo, let me know.

**Comment by belathus** [comment]
Current fuel values are listed below. I'm sure I still need to re-balance them. I did set the fuel values of fire water, hootch, rocket fuel, canola oil, oil, crystallized oil, and empowered oil to match EnderIO and Actually Additions. In addition, nutrient distillation in the zombie generator produces 800k rf while here I bump it to 1.1m since the reactant dynamo requires a second fuel.

Another thing to note: we have two types of rocket fuel, and it looks like rocket fuel from Advanced Rocketry might be really easy to make. Similarly with Hydrogen. As such, we may need to bump those two down quite a bit. We also have two types of ethanol -- Forestry's and someone else's. Forestry's ethanol power use here was predefined at 500k. I set the other to the same.
- Compression:
  - bio.ethanol=250k
  - biodiesel=500k
  - canolaoil=80k
  - chloromethane=250k
  - coal=500k
  - crude_oil=250k
  - crystaloil=560k
  - empoweredoil=960k
  - ethanol=250k
  - fire_water=1.2m
  - fuel=2m
  - hootch=360k
  - hydrogen=350k
  - oil=192k
  - plantoil=900k
  - refined_oil=1.25m
  - rocket_fuel=1.12m
  - rocketfuel=1.12m
  - syngas=250k
  - tree_oil=1m

* Reactant
  * aerotheum=1.25m
  * biomass=450k
  * blood=50k
  * blueslime=50k
  * creosote=250k
  * for.honey=120k
  * glowstone=600k
  * honey=120k
  * juice=30k
  * lifeessence=10k
  * liquid_essence=95k
  * liquidantimatter=225k
  * mobessence=500k
  * nutrient_distillation=1.1m
  * purpleslime=400k
  * redstone=500k
  * seed.oil=250k
  * seedoil=250k
  * sewage=24k
  * sludge=24k
  * xpjuice=200k

**Comment by belathus** [comment]
Okay, gonna call this good for now. We'll have to see if we can break things in a later play-through.
