### ISSUE TITLE
Grind / Crush broken spawners for  spawner shards.

### ISSUE THREAD

**Issue by Divineaspect** [belathus/Wanderlust-Renewed#117]

**Comment by belathus** [comment]
My original thought was to stop spawner shards from dropping and making someone grind the broken spawners to get them, but ActuallyAdditions does not have anything in the configs to stop the shards from dropping. As it is, the spawner changer seems like a fairly powerful tool, and you'd only need to break 4 spawners to get it. This change would reduce the amount to 2 if we give it a 1 to 1 ratio for broken spawner to spawner shards.

Another option to limit the power of the spawner changer would be to add to its blacklist. Currently, it only stops you from making iron golem spawners.

**Comment by Divineaspect** [comment]
hellcows should probably be added to this list.

We could establish a rough equivalence between the materials needed for the various spawning methods and bring the spawner changer into line with it.

I think the methods from most to least powerful/convenient are
Ender IO powered spawners
RFtools
Changed Resturbed Spawners (AA + EU)
AM2 Summoners
Cursed Earth
Changed Spawners (AA)
Resturbed Spawners

I think it's the combination of the AA + EU which is disproportionate in it's power/convenience. We can't do a lot with the EU ends of things (except  change the bit of evil drop rules), but replacing the magma cremes in the recipie with something magically advanced would do wonders  to make that harder.

**Comment by belathus** [comment]
If we were to change the drop of evil drop rules, how would you want to change it? I can remove it as a drop from wither skeletons then add a specific requirement if we want.

**Comment by Divineaspect** [comment]
common drop from boss monsters, rare from wither skeletons when killed with holy or divine effects, by an unarmored person only?

**Comment by belathus** [comment]
Looking through the damage types, Ars Magica adds a holy damage type, but the holy effect from silver Tinker's Construct tools is not its own damage type. Still, I'd love to make it drop from being killed by a silver sword. This might be difficult to do.

**Comment by belathus** [comment]
Another note: for both EnderIO's powered spawner and RFTool's spawner, I can increase the cost of spawning certain mobs. Pretty sure EnderIO's spawner is pretty crazy expensive in terms of RF (I'm unsure if this is also true of RFTools) unless that mob is common or not configured to take more power. As far as I know, I'm not capable of adjusting the cost of power using Resturbed mob spawners or changed spawners aside from the initial recipe.

ExtraUtilities's configs are a bit disappointing. The only option I have is to either enable or disable things. No whitelist, blacklist, or other customization. All I can do here is disable resturbed mobs spawners or cursed earth.

Actually Additions has a blacklist of mobs, as I mentioned before. I've added a bunch to it, but is there anything that we want that we can increase the cost of that is allowed to spawn in the RFTools or EnderIO spawner that we want to blacklist on the changed spawner? So far, I have the hell cow.

**Comment by Divineaspect** [comment]
Rftools spawner is fucking amazing, quite tricky to get set up to spawn
things safely, and has advanced resource costs. I consider it and EnderIO
to be high end lategame spawners where I don't mind if they can spawn
things not otherwise available.

Not sure about disabling resturbed spawners, but messing with the drop of
evil is a must.

actually additions has a spawner system?

Jeremiah Grimsley


"All of humanity is in peril of extinction if each one of us does not dare,
now and henceforth, always to tell only the truth, and all the truth, and
to do so promptly — right now." - R Buckminster Fuller

**Comment by belathus** [comment]
For Actually Additions, I'm talking about the spawner changer.

So far, I've changed the drop of evil to be a drop from the Wither, a rare drop from Wither Witches, and a drop from wither skeletons that are killed with holy damage from Ars Magica. I haven't quite worked out how, say, a silver sword might generate extra drops, but I'd love to figure that one out.

In regards to changing the recipe for the spawner changer, have you thought about what you want to replace the magma creams with? You said something magically enhanced; maybe it could be a group of recipes: one that uses terrasteel, one that uses philosopher's gold, one that uses demon blocks, or one that uses sunstone?
