### ISSUE TITLE
Metal Processing with Better Beginnings

### ISSUE THREAD

**Issue by belathus** [belathus/Wanderlust-Renewed#118]
@Divineaspect, we talked about making BB's smelter take seared bricks to craft and increasing the difficulty of obtaining seared bricks even further. Also, currently, the smelter allows for processing iron, which makes the bloomery less worthwhile. Did you want to disable this route of iron processing? Alternatively, shall I change the iron ore that is found in the Nether to be, say, goethite, hematite, or magnetite instead of "iron ore" to force the requirement of processing it in the bloomery?

It might require an extra step (convert abyssal iron to rockhounding ore, because I don't think that no matter how I change abyssal iron it will go into the bloomery unless I use Rockhounding's API), but this should be manageable.

Finally, the smelter looks like it is made of grey stone. If we use seared stone, I could edit the texture to be closer to the seared brick texture. If we're feeling ambitious, I could do similar to the bloomery.

**Comment by Divineaspect** [comment]
yeah the smelter needs iron removed from it, but leaving / adding all other metals, except maybe bauxite/aluminum?

The nether iron ore is processable in the bloomery already.
