### ISSUE TITLE
Blocks of Enderpearl be used as fuel for ender generator

### ISSUE THREAD

**Issue by greenking13** [belathus/Wanderlust-Renewed#122]
No boost to power, just a 4x duration.

**Comment by belathus** [comment]
Are we talking about the Extra Utilities ender generator? I don't think I have the ability to modify that.

**Comment by belathus** [comment]
This cannot be done currently. If you want to push for it, suggest it on RWTema's Github [issue tracker](https://github.com/rwtema/extrautilities). Though, he appears to barely touch that tracker. I suppose you could also try Twitter, as he is more active there.
