### ISSUE TITLE
Iridium ore does not spawn

### ISSUE THREAD

**Issue by greenking13** [belathus/Wanderlust-Renewed#125]
I feel that I can safely say that you can spawn it on THE MOON!!! Iridium ore is added by base, thermal foundation, and advanced rocketry. I'd recommend the advanced rocketry, I haven't checked the thermal foundation version.
*Cue dramatic music.*

**Comment by belathus** [comment]
I did notice that iridium was a byproduct of platinum ore processing via Thermal Expansion. I imagine other mods will (or be made to) follow suit. However, platinum ore does not spawn using the default configuration.

@Divineaspect; would you prefer that I generate platinum ore and force them to process it in a way that maximizes iridium if they need that, or should I specifically generate iridium ore somewhere?

**Comment by Divineaspect** [comment]
I think limiting iridium to rare and hostile space dimensions would be best. Otherwise platinum maximization seems like a better challenge.

**Comment by belathus** [comment]
I added platinum generation. Since you can now process platinum ore to get iridium, I'm going to consider this resolved.
