### ISSUE TITLE
Early Waystone Use

### ISSUE THREAD

**Issue by Divineaspect** [belathus/Wanderlust-Renewed#13]
I'd like to enable Early waystone use, in preparation for the worldgen feature being added to Waystones, and that means a cheaper recipe(s) for the recall scrolls.

Proposing parchment + (magical powders) generates a variable number of recall scrolls.

Early game/easily renewable magic powders should make 1 recall scroll per dust
redstone, vinteum dust, mana powder (botania)

Slightly challenging magic powders should make 3 recall scrolls per dust
glowstone, blaze powder, ender dust

Rare or precious magic powders should make 8 recall scrolls per dust
crushed dark gem, is there anything else?

**Comment by belathus** [comment]
None that I can think of. I'll start writing these recipes soon.
