### ISSUE TITLE
More potential Recipes to add

### ISSUE THREAD

**Issue by TBone311xXx** [belathus/Wanderlust-Renewed#135]
2x2 silk into string
Creature heads with workblade into respective reliquary special drops
-more that I can't currently think of

**Comment by belathus** [comment]
2x2 silk makes thread already. Are you suggesting it makes string instead of thread, or that 2x2 thread makes string?

**Comment by belathus** [comment]
Okay, since the first request is more-or-less resolved and the second is a duplicate, I'm gonna close this.
