### ISSUE TITLE
Sharp little knives and practical altars

### ISSUE THREAD

**Issue by Divineaspect** [belathus/Wanderlust-Renewed#14]
Lots of magic mods use knives to get started, and these should be available in the stone age.

- [ ] Roots Bark Knife
Flint and chipped fint in a diagonal line with a stick and the verdant sprig?

- [x] Blood Magic Sacrificial Knife
I'm  thinking a flint and a chipped flint + a congealed blood or blood drop from the tip?

- [ ] Roots Altar
Needs to not use a block of bloody gold, but what else would work to represent a core of work?

- [x] Incense Burners
You need between 2 and 4 of these for roots. The Iron they use is out of scope. I suggest a stone bowl for the cauldron replacement, what for the supports?

- [x] Blood Altar
A Diamond and Gold are right out...

**Comment by belathus** [comment]
I guess something can only have one milestone.

**Comment by Divineaspect** [comment]
Roots changes to that knife and altar aren't needed any longer.
