### ISSUE TITLE
Iron dusts should be smeltable in enderio alloy smelter??

### ISSUE THREAD

**Issue by TBone311xXx** [belathus/Wanderlust-Renewed#140]
Alloy smelter needs steel to make, so it should also be able to process iron?

**Comment by belathus** [comment]
Dust should be smeltable thanks to [this line](https://github.com/belathus/Wanderlust-Renewed/blob/master/scripts/metalsunification.zs#L229). Granted, I think I re-added the ability to smelt iron ore into an ingot by accident.

**Comment by belathus** [comment]
This should've been fixed when I stopped the metals unification script from erroring.
