### ISSUE TITLE
KABOOOM-erang? on a pickaxe?? THAT'S GOT FORTUNE 5??? Mixed enchant id's bug

### ISSUE THREAD

**Issue by TBone311xXx** [belathus/Wanderlust-Renewed#141]
![image](https://cloud.githubusercontent.com/assets/12605227/24518506/3b4ccc4e-1550-11e7-9dba-5659c49972b7.png)

**Comment by belathus** [comment]
I went through and fixed up enchantment IDs where I could. I don't know if I fixed it, but I'm gonna close this for now. If we see it crop up again, I'll happily reopen this issue.
