### ISSUE TITLE
Stick Cost Unification

### ISSUE THREAD

**Issue by Divineaspect** [belathus/Wanderlust-Renewed#143]
2 ingots for 1 stick in crafting grid?

**Comment by Alan19** [comment]
Is this for all materials or just non-wood materials?

**Comment by belathus** [comment]
For the most part, I believe the metal press will produce two rods per ingot. I think we should normalize at 1 stick for 2 ingots in the grid, and 2 sticks for 1 ingot in the press or lathe. When melting the rods, they should all return 72 mb of metal (1/2 an ingot).

**Comment by belathus** [comment]
I've decided to be slightly more generous. In the crafting grid, you get 2 sticks for 2 ingots. In a metal press or lathe, you get 2 sticks for 1 ingot.
