### ISSUE TITLE
Dragon should drop more eggs on kill, but only on unique player kills

### ISSUE THREAD

**Issue by TBone311xXx** [belathus/Wanderlust-Renewed#148]

**Comment by belathus** [comment]
Fun fact: you can use a dispenser with a water bucket to replace end portal blocks with water. Once you delete the entire portal, the next time someone goes to the End it'll spawn another ender dragon.

Seems weird that only one dragon egg can be obtained on a server without taking advantage of bugs. I'll see what I can do.

**Comment by Divineaspect** [comment]
Doesn't a new portal usage respawn the dragon?

**Comment by belathus** [comment]
From what I understand, all end portals teleport you to the same place. If there is already an open end portal in the End, a dragon will not spawn. A dragon can be respawned by crafting 4 ender crystals and placing them on the edges of the portal frame, but a respawned ender dragon will not drop another dragon egg. Pretty much the only way to get a second dragon egg via Vanilla is to destroy the end portal via the dispenser trick and kill yourself so you can enter the end portal again.

**Comment by Alan19** [comment]
I can add extra eggs to a quest
