### ISSUE TITLE
Oredict PrimalCore work tables

### ISSUE THREAD

**Issue by Alan19** [belathus/Wanderlust-Renewed#156]
They need to be oredicted so I can make a quest take any work table

**Comment by belathus** [comment]
PrimalCore does add oredictionary entries for its wooden work tables. Would this work? Do you specifically want it to have the "workbench" oredictionary entry? Are you asking specifically about the non-wooden workbenches?

 https://github.com/belathus/Wanderlust-Renewed/blob/master/oredict#L7302-L7308

**Comment by Alan19** [comment]
I didn't notice the oredict. I'll take a look at it when I get home.

**Comment by Alan19** [comment]
I don't see it in game

**Comment by Alan19** [comment]
Only the slabs are oredict ed
