### ISSUE TITLE
Pregen MineColonies base camp or supply ship instead of crafting them

### ISSUE THREAD

**Issue by belathus** [belathus/Wanderlust-Renewed#158]
I was thinking of making the base camp and supply ship both structures you find while exploring (complete with the town hall item) rather than something you make. Thoughts?

**Comment by Alan19** [comment]
That sounds pretty nice.

**Comment by belathus** [comment]
@Alan19: you said you found a base camp while exploring?

**Comment by Alan19** [comment]
Yes
