### ISSUE TITLE
Harder Grout Options to extend the Stone Age

### ISSUE THREAD

**Issue by Divineaspect** [belathus/Wanderlust-Renewed#16]
Grout can be made by smashing together in a mortar and pestle (the primal core one)

- [x] Carbonate + Ash + Mud
- [x] Clay + Mortar + Silt
- [x] Gravel + Gunpowder + Earthwax
- [x] Terraclay + Bonemeal + Silt

**Comment by belathus** [comment]
I need to edit the silt part of the recipes, as I do not have the metadata for it, currently.

**Comment by Divineaspect** [comment]
The Combo smelting thingie from ender io should also work with them directly into seared bricks.

**Comment by belathus** [comment]
Easy enough to implement. It'll just take editing the alloy smeltery xml file in the EIO configs. While I'm in there, any other recipes we wish to add to it?
