### ISSUE TITLE
Chest and Fishing Loot Tables

### ISSUE THREAD

**Issue by belathus** [belathus/Wanderlust-Renewed#163]
I just looked through the loot tables I can edit. I'll download the listing and put it in Github. I can edit the following:

* Actually Additions: jam house chest and lush caves chest
* Ars Magica (do these actually spawn?)
  * mage tower chest
  * rare mage tower chest
* Astral Sorcery
  * Shrine chest
* Botania
  * Gaia guardian (1 and 2) drops
  * a bunch to additions to vanilla loot tables
* Forestry
  * Naturalist's villager chest
* Immersive Engineering
  * Engineer's villager chest
  * Stronghold library
  * Village blacksmith
* Level Up
  * Digging
  * Fishing
* Vanilla Minecraft: huge list
  * Chests
    * abandoned mineshaft
    * desert pyramid
    * end city treasure
    * igloo chest
    * jungle temple
    * jungle temple dispenser
    * nether bridge
    * simple dungeon
    * spawn bonus chest
    * stronghold corridor
    * stronghold crossing
    * stronghold library
    * village blacksmith
  * Fishing
    * Junk
    * Fish
    * Treasure
* The BetweenLands
  * Common chest loot
  * Common pot loot
  * Dungeon chest loot
  * Dungeon pot loot
  * Music Disc

**Comment by Divineaspect** [comment]
No the ars structures aren't spawning.
we can edit the levelup lists, sweet.

**Comment by belathus** [comment]
I've removed a bunch of stuff from the digging list for Level Up. It is interesting to note that all of LevelUp's digging drops are affected by a fortune enchantment on the shovel.

The rare category is pretty bare: diamond with a weight of 1, and 4 enchanted stone tools with a weight of 2 each. I'm thinking of removing the stone tools and adding PrimalCore's flint tools with enchantments. In addition to that, I'd like to add vanilla quartz, PrimalCore's obsidian shards, and maybe a bunch of the Biomes O' Plenty gems.

The uncommon category is also pretty bare: iron ingot, gold ingot, slime balls, and bowls. Maybe add various metal nuggets to this group.

Some things I've added:
* Common
  * PrimalCore's Plant fiber, with a weight of 20
* Uncommon
  * TConstruct slimes, weights: blue: 4; blood: 3; magma: 2; purple: 1
* Rare
  * PrimalCore's Blood Opal, weight: 1

**Comment by Alan19** [comment]
Should we include the loot inside the loot doc?

**Comment by belathus** [comment]
What loot doc?

**Comment by Divineaspect** [comment]
the guidelines I made  for Alan for dungeon loot.

**Comment by Divineaspect** [comment]
Add feathers to  uncommon

**Comment by belathus** [comment]
Added, with a weight of 10.

**Comment by belathus** [comment]
This issue is nearly a year old and most of the conversation is no longer applicable, since we pulled LevelUp. I'll be opening a new issue for the current loot tables.
