### ISSUE TITLE
dungeon tactics diamond sword not input for bound blade?

### ISSUE THREAD

**Issue by Divineaspect** [belathus/Wanderlust-Renewed#164]
and we don't seem to be able to craft a dt sword into it's vanilla  counterpart.

**Comment by Divineaspect** [comment]
either we should disable crafting the dungeon tactics diamond sword, and use advanced crafting only with a craft by itself to exchange, or shift to vanilla crafting the basic sword.

**Comment by belathus** [comment]
I'm thinking of going with a slightly different approach. The primary version of the sword will be the PrimalCore workblade. The workblade can be directly turned into a diamond sword, which can in turn be directly turned into the Dungeon Tactics version.
