### ISSUE TITLE
Automated Sticks

### ISSUE THREAD

**Issue by greenking13** [belathus/Wanderlust-Renewed#170]
Automate sticks via bound axe and planks. Or if we toss planks into crusher to make sticks.

**Comment by belathus** [comment]
I don't want the crusher/sagmill/grinder/pulverizer to make sticks. It is most appropriate for those machines to make sawdust. The sawmills should make sticks, though.

I can add this to Advanced Rocketry's sawmill if it isn't there already. I can't do much to Thermal Expansion's.
