### ISSUE TITLE
Custom darkstone vengence tools

### ISSUE THREAD

**Issue by Alan19** [belathus/Wanderlust-Renewed#175]
Add an alternative recipe for darkstone tools that would give looting 5 and vengence 2 by replacing the sticks with undead sticks (the ones from the evilcraft tree), replacing the darkstone with diamonds and 3 blood shards to empty spaces in the top two rows.

**Comment by belathus** [comment]
I'm pretty sure the vengeance pickaxe, in recent versions, specifically prevents you from removing the vengeance enchantment. Do we know if we can do the same thing with other tools?

**Comment by Alan19** [comment]
I don't think so but if we can't, we can give it Fortune 3 instead of 5.
