### ISSUE TITLE
lathe for stick manufacture?

### ISSUE THREAD

**Issue by Divineaspect** [belathus/Wanderlust-Renewed#177]
howabout the lathe to make sticks via machine?

**Comment by belathus** [comment]
The lathe is a simple input/output device isn't it? just put stuff in the input, provide power, get stuff in output? I'll start working on that, then.

**Comment by belathus** [comment]
https://github.com/belathus/Wanderlust-Renewed/commit/aa42c0814430204805700dbd66e7b058a763b2b3

**Comment by belathus** [comment]
Though, I admit that a lathe would probably be more appropriate for making tool rods. I guess it could be an interesting way to make TiC tool rods. Differentiating between tough tool rods and normal tool rods might be tough.
