### ISSUE TITLE
Custom Bees

### ISSUE THREAD

**Issue by belathus** [belathus/Wanderlust-Renewed#192]
Just adding this issue to track ideas for new bee hives and bee species.

I've already added bees that could be used to produce EvilCraft blood and dark gems (cruetus, tenebra, and impero bees).

Perhaps add Abyssalcraft themed bees, especially as hives to AbyssalCraft dimensions. could be useful for producing dreadium and coralium, and metals in their crystallized forms. I wouldn't mind if the hive bees produced something useful just for getting into the AbyssalCraft dimensions.

Perhaps add space bees; these will be found on various planets found throughout the systems via Advanced Rocketry. They could produces resources like oxygen, fuel, titanium, and iridium if necessary.

**Comment by Alan19** [comment]
- [ ] Lemon-Lime Soda
- [ ] Energy Drinks
- [ ] Gorgon Drink
- [ ] Candy
- [ ] Razorblade

**Comment by belathus** [comment]
* [ ] Porcine - Pig bees: produces pig products, such as pork chops (possibly truffles?)
* [ ] Equine - Horse bees: produces leather and horse meat
* [ ] Canine - Wolf bees: produces wolf pelts and wolf meat
* [ ] Galline (or maybe poultry): Chicken bees: feathers, chicken, eggs
* [ ] Caprine - Goat bees: whatever the goat products are
* [ ] Ovine - Sheep bees: produces wool and mutton
* [ ] Ovine Atre - These are the nether sheep. Produces ovis atre wool and mutton

**Comment by Alan19** [comment]
- [ ] Abyssalcraft bees - Liquids, basic resources, statues and coins

**Comment by Alan19** [comment]
Electrobob's Wizardry Bees

**Comment by belathus** [comment]
Closing this until we re-add Gendustry.
