### ISSUE TITLE
Incorrect Case Config File List

### ISSUE THREAD

**Issue by Alan19** [belathus/Wanderlust-Renewed#198]
- [x] aroma1997 lowercase configs
- [x] Bibliocraft.cfg
- [x] Botania.cfg
- [x] Morpheus.cfg (needs to be changed so it uses 1.10 settings as well)
- [x] Stackie.cfg
- [x] StorageDrawers.cfg
- [x] Waystones.cfg

**Comment by Alan19** [comment]
I forgot to mention the uppercase JEI folder needs to be deleted as well

**Comment by belathus** [comment]
Anything else?

**Comment by Alan19** [comment]
That should be it

**Comment by Alan19** [comment]
integrationforgegoing.cfg is an incorrect version of IntegrationForegoing
