### ISSUE TITLE
Ore production and weights (IE: how to handle the Laser Drill)

### ISSUE THREAD

**Issue by belathus** [belathus/Wanderlust-Renewed#203]
We have agreed that devices such as the laser drill, orechid, mineralis ritual, and so on should only produce "common" ores. Each type of generation might be able to produce one unique ore type that the other methods do not produce.

The excavator and asteroid mining missions will be separate from this, as each excavator built or mission conducted only produces a fixed set of ores that is way more limited than the above-mentioned ore generators.

The current list (and weights) is below (italicized items do not appear on Divine's list below):
* Aluminum: 600
* Anthracite: 2000
* _CertusQuartz_: 500
* _Coal_: 3200
* Copper: 1100
* _Dark Gem Ore_: 300
* _Diamond Ore_: 180
* _Emerald Ore_: 100
* Goethite: 1000
* _Gold_: 550
* Lapis: 140
* Lead: 1000
* _Mithril_: 1
* _Nickel_: 270
* _Platinum_: 2
* Redstone: 700
* _Ruby_: 400
* _Sapphire_: 400
* Siderite: 2500
* Silver: 180
* _Sulfur_: 600
* Tin: 1500
* _Uranium_: 55
* Zinc: 300

And, for comparason, here is @Divineaspect's proposed list from Discord:
* Aluminum: 3
* Copper: 4
* Gold: 1
* Iron (Goethite, Siderite, etc): 5
* Lapis Lazuli: 2
* Lead: 2
* Redstone: 3
* Silver: 2
* Tin: 2
* Zinc: 1

To fill it out, I'm thinking of adding coal, anthracite, bituminous, and lignite to the list; each at a equal or higher weight than iron (with anthracite being the least common), and perhaps adding common gems, such as peridot, malachite, topaz, and amber; and finally, saltpeter/nitre. I'd add sulfur, but as far as I am aware, we don't have a sulfur ore.

As far as unique ores, I'd want to do magical or precious ores for magical methods of producing ore (Mineralis, Aevitas perk, treasure shrine, orechid, and so on) such as mithril, platinum, or gold, and for mechanical methods of making ore (laser drill; any others?), it can grab things like uranium, rutile, or nickel.

I'll list all possible ores that we haven't talked about below (Note: as of right now, I cannot modify the ores produced by the orechid ignem):
* Abyssalnite
* Amethyst
* Aquamarine
* Ardite (produced by the orechid ignem)
* Burnium
* Certus Quartz
* Cobalt (produced by the orechid ignem)
* Coralium
* Coralium Stone
* Dark Gem
* Dilithium (I want to move this exclusively to asteroids and maybe other planets)
* Dreaded Abyssalnite
* Electrum
* Endimium
* Liquified Coralium
* Nether Quartz (produced by the orechid ignem)
* Niobium
* Osmium (there is an issue open specifically to talk about this one; I want it to be a "must go to space" ore)
* Pearlescent Coralium
* Plutonium
* Rime (NEX)
* Rock Crystal (Astral Sorcery)
* Ruby
* Sapphire
* Starmetal
* Tanzanite

**Comment by belathus** [comment]
Just to make it clear, the orechid ignem only produces 3 ores, and I cannot modify this at all (yet): cobalt, ardite, and nether quartz.

**Comment by Divineaspect** [comment]
I thought I'd kicked Gold in at 1, but I see I didn't.

**Comment by belathus** [comment]
This has been implemented.
