### ISSUE TITLE
Materials being Autoenchanted

### ISSUE THREAD

**Issue by Divineaspect** [belathus/Wanderlust-Renewed#23]
The Enchanter is maybe available, but what about making some materials have inherent enchantments when crafted?

Part of my Motivation is to increase the desire to get into magic to remove the negatives.
It also increases the value of anvils.

Copper: Breaking 1
Tin: Breaking 2

Gold: Affluency 2 / Prospector
Bronze: Sharpness 1, Efficiency 1 / Unbreaking 1
Brass: Flame Touch /Breaking 1
Lead: Poisontip 1 /  (Armor) Protection 1 / Breaking 1
Silver: Smite 1, Fortune 1, Breaking 1
Platinum: Smite 1, Looting 2 / Fortune 2, Prospector 2

Adamantine: Breaking 2
Aquarium:  (Armor) Blast Protection 1, Depth Strider
Cold Iron:  (Armor) Fire Protection 2 / Frost Walker
Cupronickel: ?
Electrum: Smite 1
Invar: Sharpness 1, Unbreaking 1 / (Armor) Fire Protection 2, Unbreaking 1
StarSteel: ?

Don't rush ahead and add this Belathus, I want to discuss  it first.

**Comment by Alan19** [comment]
Doesn't tin already have extremely low durability on tools?

**Comment by belathus** [comment]
One particular problem I can see right away is that you can remove the negative enchantments simply by crafting two broken tools together.

**Comment by Divineaspect** [comment]
I did not think of that.

**Comment by Divineaspect** [comment]
This issue has mutated into #124
