### ISSUE TITLE
Libvulpes' iron dust can be smelted in a furnace

### ISSUE THREAD

**Issue by Alan19** [belathus/Wanderlust-Renewed#230]

**Comment by Alan19** [comment]
Iron ore can be grinded in a quartz grindstone to double it. I think I got a good amount of them from the recurrent complex meteors.

**Comment by Alan19** [comment]
We should probably remove being able to grind iron ore into dust in the quartz grindstone

**Comment by Divineaspect** [comment]
Howabout adding a bronze gear to the grindstone recipe?

**Comment by belathus** [comment]
The grindstone currently requires a brass gear.

**Comment by Alan19** [comment]
I think it's fine then. It's manual grinding so it's not that easy to large amount of iron from it, especially because you can only grind the vanilla iron (unless you have an autoclicker).

**Comment by belathus** [comment]
We have a recipe to make goethite and limonite into vanilla iron, but it costs XP to do so. I think I'm okay with it the way it is, but I do want to limit how much iron ore spawns in Recurrent Complex structures.
