### ISSUE TITLE
Add several varieties of coke

### ISSUE THREAD

**Issue by belathus** [belathus/Wanderlust-Renewed#235]
Since we have Rockhounding: Ore Tiers, we have several varieties of coal you can find in the world: lignite, bituminous coal, and anthracite coal.

As per #108, we should enable turning all of these varieties of coal into coke, except Lignite (as that can be refined into bituminous coal, which then could be turned into coke).

But, we can go a step further. All varieties of coke should be able to be turned into a blood-soaked version, which doubles the fuel value of the coke.

Oh, yeah, and make sure all of these varieties of coke can be used in Immersive Engineering's blast furnace.

Blood-waxed coal is an odd-ball for the blast furnace because it can be made with charcoal, so it follows charcoal's fuel value in the blast furnace. Otherwise, fuels have about 3/8ths the fuel value in the blast furnace compared to the regular furnace.

| Fuel | value | BF | block | BF-block |
| ----------- | ------- | --- | --- | --- |
| Charcoal | 1600 | 300 | 16000 | 3000 |
| Lignite | 1200 | n/a | 12000 | n/a |
| Bituminous Coal | 2400 | n/a | 24000 | n/a |
| Anthracite Coal | 3200 | n/a | 32000 | n/a |
| Coke | 3200 | 1200 | 32000 | 12000 |
| _Bituminous Coke_ | 4800 | 1800 | 48000 | 18000 |
| _Anthracite Coke_ | 6400 | 2400 | 64000 | 24000 |
| Blood-Waxed Coal | 3200 | 600 | 32000 | 6000 |
| _Blood-Waxed Coke_ | 6400 | 2400 | 64000 | 24000 |
| _Blood-Waxed Bituminous Coke_ | 9600 | 3600 | 96000 | 36000 |
| _Blood-Waxed Anthracite Coke_ | 12800 | 4800 | 128000 | 48000 |

**Comment by Alan19** [comment]
Is there any sense in making coke and blood waxed variants for PrimalCore charcoal?

**Comment by belathus** [comment]
I won't make coke variants of PrimalCore's charcoal, but blood-waxed variants could happen.
