### ISSUE TITLE
Remove iron ore from recurrent complex structures

### ISSUE THREAD

**Issue by belathus** [belathus/Wanderlust-Renewed#242]
The way I see it, we can do this using several methods.

1. A universal transformer that turns all vanilla iron ore into something else (goethite or limonite?). This is by far the easiest solution, I think.
2. Disable structures that might spawn with iron ore in them. Since recurrent complex has a ton of structures, this might be a little time consuming.
3. Disable all Recurrent Complex structures and just use structures we make. I admit I'm somewhat fond of this idea, but I recognize that this'll likely require more work than the idea above.

**Comment by Alan19** [comment]
Didn't you make a transformer that does this?

**Comment by belathus** [comment]
I did. Do we know if it works?

**Comment by Alan19** [comment]
We can gen some RC meteros and check

**Comment by belathus** [comment]
Alright, this clearly works.
