### ISSUE TITLE
Maze breaker turned into a tinker tool or tool part

### ISSUE THREAD

**Issue by belathus** [belathus/Wanderlust-Renewed#259]
The idea is that a maze breaker is made from some unknown material that has special properties.

I'm thinking that the mazebreaker should have a recipe made of three "mazebreaker ingots" and two sticks and that the only way to get mazebreaker ingots is to uncraft the mazebreaker. Then, you can use the mazebreaker's ingots to make a tool.

As far as tool properties, I'm thinking that the mazebreaker should have a high mining speed and durability akin to diamond. It should have a cobalt mining level.

Ideally, I want the mazebreaker to come with the Luck modifier (level 2) if I can manage it. It could also have a property that increases its mining speed when mining something that takes a significant amount of time to break, such as obsidian.

color: a pale green `#bbd7bb`
* **Head:** 
  * 1561 durability
  * 13.0 speed
  * 7.45 damage
  * cobalt mining level
  * Traits: ?
* **Handle:**
  * 1.5 multiplier
  * +250 durability.
  * Traits: ?
* **Extra part:**
  * +50 durability
  * Traits: ?
* **Bow:**
  * 0.75 draw speed
  * 1.3 range (arrow speed?)
  * 4 bonus damage
  * Traits: ?

**Comment by Alan19** [comment]
I went through the trait documentation and we need to use the ``GetMiningSpeed`` function and access the block information from the ``IBlock`` field of the ``PlayerBreakEvent``. It looks like we just need to set the ``newSpeed`` field based on the properties of the ``IBlock`` to speed up the block breaking.
