### ISSUE TITLE
Mob Stages

### ISSUE THREAD

**Issue by Divineaspect** [belathus/Wanderlust-Renewed#266]
* [x] **mansiontraveller** - granted for finding and clearing a mansion
-Trollager
-Mimics

* [x] **seatraveller** - granted for killing a guardian
-Hammerhead Shark

* [x] **dimensionaltraveller stage** - granted for leaving the overworld
-Endermen
-Skeletons, 
-Zombies

* [x] **nethertraveller stage** - granted for entering the nether
-Wither Witches, Wither Cat

* [x] **twilighttraveller stage** - granted for visiting the Twilight Forest
-Grove Sprite
-Bewitched Tome

* [x] **erebustraveller** - granted for entering the erebus
-Mother Spider, Baby Spider

* [x] **betweentraveller** - granted for entering the betweenlands
-NetherEX's wight

* [x] **endtraveller** - granted for entering the end
-Endermini
-Concussion creepers

* [x] **stoneage stage** - granted for making chipped flint tools
-Steppe Wolves
-Filch Lizard

* [x] **fireage stage** - granted for making or using a furnace
-Creepers

* [x] **alchemyage stage** - granted for making any potion type
-Blue Slimes
-Witches

* [x] **explosionage stage** - granted for making TNT or Nitor
-Festive Creepers

* [x] **bronzeage stage**
-Skeleton Warriors
-Treasure Slimes

* [x] **silverage stage**
-Brain Slimes
-Blazing Juggernauts
-Wizards

* [x] **ironage stage**
-FallenKnight, FallenSteed
-Ferrous Wroughtnaught
-Lost Miner
-Wandering Merchant

* [x] **flightage** - granted for taking flight or launching a rocket (orbit dimension?)
-Rocket Creepers

**Comment by belathus** [comment]
I'm not sure how I can latch on to the mansion event. I'll look into it.

**Comment by belathus** [comment]
Alright, there is a stage for all of these guys now. Now I just need to add conditions for them.

**Comment by Alan19** [comment]
I'll look into making conditions for the rest of the stages.
