### ISSUE TITLE
[Random Things] Use Artisan Worktables's chemistry table to make fertilized dirt

### ISSUE THREAD

**Issue by belathus** [belathus/Wanderlust-Renewed#267]
Current ideas for ingredients:
* Rustic: fertile soil
* Forestry: apatite
* sulfuric acid (IRL: phosphoric rock [apatite] and sulfuric acid make "super fertilizer")
* Xeno's Reliquary: fertile essence (made with a rib bone, catalyzing gland, slime pearl, and cactus green)

**Comment by Divineaspect** [comment]
It should use Rustic's Fertile Soil as it's baseline (as that's weaker), and already includes basically, adding bonemeal.
