### ISSUE TITLE
Making Chisel Metal Blocks Usable

### ISSUE THREAD

**Issue by Alan19** [belathus/Wanderlust-Renewed#29]
It might be a good idea to disable chisel metal blocks from being chiseled into the resource/vanilla version while making the recipe a block of that metal surrounded by stone bricks (could be anything else) and the metal block is refunded. That way, players can use metal blocks for decoration without using too many resources while not breaking the game.

**Comment by belathus** [comment]
Due to issues with Chisel and ModTweaker, I'm gonna close this.
