### ISSUE TITLE
Adventures and backpacks and stuff

### ISSUE THREAD

**Issue by TBone311xXx** [belathus/Wanderlust-Renewed#294]
- [x] Add Boxes of eternal closure 
- [x] Enchanted Books
- [x] Maze map focus
- [x] Charms of Keeping / Life
- [x] Undying totem?
- [x] Maps
- [x] Divining Rods
- [x] Minecart
- [x] Boat
- [ ] Tutorial Books (thaumcraft, Botania, Evilcraft etc.)
- [x] Buckets, water/;lava/empty
- [ ] Various niche weapons? (Key of the King's Law, Rod of the Hells, Caster Gauntlet etc.)
- [x] Broken Spawners
- [x] Cyberware drops (for hunting backpack)
- [x] DungeonTactics Traps
- [ ] Electroblobs spellbooks / scrolls / wands / upgrades /arcana tomes / robes
- [x] Waystones  / scrolls
- [x] Soul vials
- [ ] Some stuff from the Erebus which I haven't explored yet
- [x] Weather containers?
- [x] Shaders / grabbags
- [ ] Natures Compass / Compass / daylight thingy
- [x] Quark Ancient tomes
- [x] Quark runes
- [x] Sqamp Talisman
- [x] Music discs

**Comment by belathus** [comment]
Alright. I have some issue with a few select items on this list. Particularly: tutorial books should go in the Enchiridion library (Hotkey: L). Similarly with EBWizardry's spellbooks.

... that is all. Most of the rest seems sound to me.

**Comment by belathus** [comment]
Interestingly, the music discs are specifically rejected from the adventuring backpack...
