### ISSUE TITLE
Gear Casts can't be made with Aluminum Brass

### ISSUE THREAD

**Issue by Alan19** [belathus/Wanderlust-Renewed#297]

**Comment by belathus** [comment]
Where most cast can be made from aluminum brass?

**Comment by Alan19** [comment]
Yes. However, since the cast melts back into gold (if I recall correctly), we should either disable the melting recipe or make leave the recipe as is.

If we do the former, we should make it craftable with aluminum brass and brass.

**Comment by Divineaspect** [comment]
casts cannot be melted back into gold

**Comment by Alan19** [comment]
Looks like only the EnderIO gears has that issue. I'll add some scripts to fix it.
