### ISSUE TITLE
Custom Roguelike Dungeons

### ISSUE THREAD

**Issue by Alan19** [belathus/Wanderlust-Renewed#30]
- [x] Abyssalcraft

- [x] Botania

- [x] ~~Futurepack~~

- [ ] ~~Embers + Roots~~

- [ ] Immersive Engineering + Esteemed Innovation + Cyberware (Maybe Cyberware can go with FuturePack)

**Comment by Divineaspect** [comment]
Lets make a Dwarfy One with Embers Content, roll the Roots and Botania ones together into the tree dungeons  belathus was  considering, the  last group could probably be broken out completely into separate dungeons.

**Comment by Alan19** [comment]
I'm going to try overriding the rooms

**Comment by Alan19** [comment]
Rooms override doesn't work

**Comment by Alan19** [comment]
Block selection for Abyssalcraft and FuturePack (mostly) finished. I'm going to start customizing the loot.

**Comment by Alan19** [comment]
Since we're moving to all dungeons having the same loot and the dungeons we're making are just aesthetically different, I'm going to check off the dungeons with completed designs.

**Comment by Alan19** [comment]
Loot is finished, starting to add mobs

**Comment by Divineaspect** [comment]
Embers and Roots aren't in the pack any more, so lets shift this to a new issue to add "tech dungeons" @Alan19
