### ISSUE TITLE
Thaumcraft Mob Gating

### ISSUE THREAD

**Issue by Alan19** [belathus/Wanderlust-Renewed#300]
Divine suggested Crimson Portals, Pechs, and Wisps could be gated. What should we gate them behind? Silver or Thauminomicon?

**Comment by FreneticScribbler** [comment]
Thaumonomnomcon I reckon, I'd rather not be bothered by the damn things.

**Comment by Divineaspect** [comment]
Creating or using Salis Mundus preferably

**Comment by belathus** [comment]
I was thinking Salis Mundus.
