### ISSUE TITLE
Clean up EBWizardry mana flash recipe

### ISSUE THREAD

**Issue by Alan19** [belathus/Wanderlust-Renewed#314]
I could probably use wildcards instead of defining each crystal type?

**Comment by belathus** [comment]
I mean... there is no reason for us to change it, since it is already built into EBWizardry. I just thought it was funny he did it that way.

**Comment by Alan19** [comment]
I thought it was a recipe I wrote a while ago.

**Comment by Alan19** [comment]
Should I close this issue?
