### ISSUE TITLE
Flint Axe needs default enchantment

### ISSUE THREAD

**Issue by Divineaspect** [belathus/Wanderlust-Renewed#34]
It's otherwise inferior to both flint hatchets.
Efficiency 1 & Unbreaking 1?

**Comment by belathus** [comment]
So, I believe I actually figured out how to adjust durability of tools; as such, I can make the flint axe have significantly more durability than hatchets by either adjusting the axe's durability up or the hatchets' durability down. Alternatively, or in addition to, I could, as an example, make the simple tools repairable in the crafting grid. The hatchets may be repairable with sticks and branches while the axe is repairable with flint (point in the hatchet's favor), but the axe retains its enchantments when repaired while the hatchets do not.

Stuff like this does involve intricate functions in CraftTweaker that are poorly supported, but I can make them work in the current version. As you know, I plan on offering Jared fixes if I can work them out in the form of pull requests.

**Comment by Divineaspect** [comment]
This would be a superior option for the axe.
Repairing with Flint, Keeping it's Enchantments... If we had a way to enchant them early.

**Comment by belathus** [comment]
We have books from loot bags. I was considering allowing you to apply an enchantment this way without an anvil, somehow. I haven't worked out exactly how it'd work. It might be limited to a single enchantment, or will never allow an enchantment beyond level 1, or something along those lines.

Alternatively, the pre-iron anvil that PrimalCore might introduce?

**Comment by belathus** [comment]
Well, I think I can safely close this issue.
