### ISSUE TITLE
Nether Monster Mobtweaking

### ISSUE THREAD

**Issue by Divineaspect** [belathus/Wanderlust-Renewed#37]
Making all the nether monsters harder.
I'm thinking a base of +50% health and +30% damage.

**Comment by Alan19** [comment]
Should drops be increased to compensate?

**Comment by belathus** [comment]
Zombie pigmen, wraiths, demon animals, nether silverfish, blazes, fire elementals, and skeletons (including wither skeletons) that spawn in the nether all have a 50% health boost and either a speed boost (40%-60%; weight: 1) or a damage boost (+2 to +4; weight: 2). I specifically omitted nitrocreepers and ghasts, though I can see giving ghasts a damage boost if we want it.

**Comment by belathus** [comment]
Well, more specifically, any of these mobs that don't spawn in the overworld receive these boosts. It isn't just the nether that gives them these boosts.
