### ISSUE TITLE
Mob Properties, Special AI

### ISSUE THREAD

**Issue by Divineaspect** [belathus/Wanderlust-Renewed#39]

**Comment by belathus** [comment]
I'm assuming we're considering adding Special AI. Lets do this in the 0.7-Dev update.

**Comment by belathus** [comment]
Man, you can do a lot of neat stuff with this. Wolves can automatically eat rotten flesh from zombies they kill to heal themselves and be set to avoid explosions. I love the idea of the throw and throw player AI. Charge, Jump, Leap, etc. will definitely make mobs tougher to deal with. Shamans could be amazing.

At the very least, I want to apply some of these AIs to Ars Magica mobs, if we can. I would love to have an occasional spawn of a group of dark mages with a shaman mage in the group, or a 'summoner' mage that spawns elementals using the spawner AI with special NBT.
