### ISSUE TITLE
Normalize Dungeon Tactics Loot Bags

### ISSUE THREAD

**Issue by Divineaspect** [belathus/Wanderlust-Renewed#44]
I propose that we normalize dungeon tactics loot bags.

I'm asking the author for some new features, if we don't get them, we can make do.

**Comment by Divineaspect** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2467962-1-10-2-dungeon-tactics?page=4#c71

**Comment by belathus** [comment]
I added a ton of things to the existing bags: the ore bag now drops ingots, including modded ingots such as copper, nickel, tin, zinc, silver, and aluminum; it also drops BoP gems (but not the amethyst). The food bag includes a variety of HarvestCraft foods. The tool bag no longer drops diamond tools, but now drops flint and quartz tools, including workblades, shears, and gallaghers.

Hopefully the metadata stuff works; the original bags did not include anything that had metadata, so I had no examples to work off of.

**Comment by belathus** [comment]
@Divineaspect, take a look and tell me if there is anything you think I should add/remove from these lists: https://github.com/belathus/Wanderlust-Renewed/blob/master/config/dungeontactics.cfg#L99-L183

**Comment by Divineaspect** [comment]
Bronze Tools?

**Comment by belathus** [comment]
I have Forestry's survivalist tools; I can add normal bronze tools, too.

**Comment by Divineaspect** [comment]
The One Probe

**Comment by Divineaspect** [comment]
kit bags

**Comment by belathus** [comment]
I noticed we can add stuff to the book bags and the potion bags that aren't enchanted books or potions. My immediate desire was to add the Enchiridion books to the book bag, but there isn't a way to add NBT data in the configs, making this currently impossible.
