### ISSUE TITLE
List of things that need to be verified

### ISSUE THREAD

**Issue by belathus** [belathus/Wanderlust-Renewed#48]
- [x] Tent Mallet recipe is changed.
- [x] Extra shield recipe that uses bronze
- [x] Smelting iron ore in a furnace results in a slagiron ingot
- [x] The only way to process slagiron is to hit it with a crack hammer, which returns an iron nugget.
- [x] Spice of Life is less harsh
- [x] Blood chests are craftable with a mending book
- [x] Most Nether mobs hit harder or are faster
- [x] Dryads drop menril and witchwood saplings
- [ ] Add more to this list as untested changes are made
- [x] Generation of Desert Nova
- [x] Generation of Tarma Root
- [x] Generation of Wakebloom
- [x] Generation of liquid essence geodes
- [x] Generation of menril resin geodes
- [x] The silver sword and iron sword recipes for the Dagger of Sacrifice are nearly identical (I'm looking for blood consumed, speed of consumption, and required tier)
- [x] Crafting iron ore from limonite and goethite ore costs XP, and is barred when you don't have enough XP.

**Comment by TBone311xXx** [comment]
Desert nova and tarma root generate

**Comment by Divineaspect** [comment]
This is now all verified.
