### ISSUE TITLE
Enchiridion Books

### ISSUE THREAD

**Issue by belathus** [belathus/Wanderlust-Renewed#49]
- [x] Add Enchiridion
- [x] Write a book that states where to find silty dirt. That list includes: tundra, cherry blossom grove, snowy forest, lavender fields, and prairie
- [x] Write a book that details where ore is found. For example, hematite is more common in cold biomes, magnetite is more common in hot and sandy biomes. We can also state the approximate height (Y-Level) at which the ores spawn.
- [ ] Guide: "Getting Through the Stone Age" - Sections: Gathering food (talk about Spice of Life's configurations), Tools of the Trade (talk about making tools, from flint hatchets to making pickaxes and work blades), Lighting Up the World (talk about torches and lighting), Ore Processing (Making the furnace, smeltery, crucible)

**Comment by belathus** [comment]
Some possible things to talk about in the food section: Cooking for Blockheads

**Comment by Alan19** [comment]
Getting through the Culinary Age!

**Comment by belathus** [comment]
Enchiridion. Hah. Closing this.
