### ISSUE TITLE
Rec Complex transformers adding ore to stone clumps on surface

### ISSUE THREAD

**Issue by Divineaspect** [belathus/Wanderlust-Renewed#50]
Including  vanilla iron.

**Comment by belathus** [comment]
I experimented with transformers yesterday and learned that they're pretty easy. They're also pretty neat. I added a stone clump on the surface that had some iron and copper ore. I may work on this more tonight.

**Comment by Divineaspect** [comment]
This is no longer an issue, as we have annother gate on iron now.
