### ISSUE TITLE
Adamantine additional uses

### ISSUE THREAD

**Issue by Divineaspect** [belathus/Wanderlust-Renewed#59]
- [x]  Darksteel
- [x] Chunk Loader (Persistant Bits)
- [ ] bound Blade and Tools
- [x] Battlemage armor: replace obsidian with Adamantine.

**Comment by belathus** [comment]
After looking through Blood Magic's ModTweaker support, I've noticed that there is currently no way to edit a recipe in the Alchemy Array, so I can't currently change the bound tools' recipes.

**Comment by belathus** [comment]
With Base Metals pulled, this issue is obsolete.
