### ISSUE TITLE
Mod Additions for 0.7

### ISSUE THREAD

**Issue by Divineaspect** [belathus/Wanderlust-Renewed#63]
Special AI (as per #39)
https://minecraft.curseforge.com/projects/special-ai?gameCategorySlug=mc-mods&projectID=224301

Harder Farming (Increases Drops from animals, auto breeding, slower growth to adulthood)
https://minecraft.curseforge.com/projects/harder-farming

Hard Lib (for Harder Farming)
https://minecraft.curseforge.com/projects/hardlib

Expanded Industry (Wooden Hoppers, as well as a few other logistic options)
https://minecraft.curseforge.com/projects/expanded-industry

Ore Flowers
https://minecraft.curseforge.com/projects/ore-flowers

**Comment by Alan19** [comment]
Are we going to be using ore flowers because the soil sampling kit isn't functional yet?
