### ISSUE TITLE
Uses for Aquarium and Star Steel

### ISSUE THREAD

**Issue by Alan19** [belathus/Wanderlust-Renewed#66]
Maybe aquarium can be used for EnderIO's enchanter to make depth strider/respiration/aqua affinity books. I don't know what to do for star steel though.

**Comment by belathus** [comment]
An alternate material for the mending enchantment, since Star Steel self repairs?

**Comment by belathus** [comment]
Also, aqua affinity takes a lilypad. Depth strider takes prismarine. Respiration takes empty bottles. Aquarium blend takes prismarine, so everything here is cheaper than aquarium ingots. Do you want me to replace a cheaper recipe with a more expensive one just to use aquarium?

I wouldn't mind using Star Steel for some late game magical machines or something. I'll have to think about it though.

**Comment by Divineaspect** [comment]
make Aquarium take less xp then other materials in the enchanter to get those enchantments
Aquarium alternate recipies for evilcraft's infinite water block, that magic chalice thing from reliquary, 

Star Steel dust + 8 iron dust make 9 steel dust.
Star Steel Gear for Essence Refiner, and maybe the rocket assembler?

Once we get the AM update we should be able to soon add aquarium and starsteel to the spell crafting altar.

**Comment by Alan19** [comment]
Respiration seems way too cheap

**Comment by Alan19** [comment]
Maybe from 8 levels to 4

**Comment by Alan19** [comment]
Needs to be tested

**Comment by Alan19** [comment]
Having multiple recipes for the same enchant is not implemented properly. Should the altered recipes be kept? @Divineaspect
