### ISSUE TITLE
Menril Saplings, Witchwood Saplings, and other magical trees

### ISSUE THREAD

**Issue by belathus** [belathus/Wanderlust-Renewed#7]
We already decided that Menril saplings will not be in world generation. Witchwood is blanket removed due to the way Ars Magica 2's configs work (unless we re-add it using a separate method).

Currently, I am thinking that we make a nature-themed dungeon via either Recurrent Complex or Roguelike Dungeons, then populate their loot tables with magical trees.

Alternatively, or in addition to, we can add a recipe. For example, menril resin can be a thing that we find in world generation. Perhaps in the Deep Dark. Then put that menril resin in a TConstruct basin with a sapling to make menril saplings. Similarly, for witchwood, we can use Ars Magica's liquid essence to make witchwood. When Thaumcraft is released, we can do similar for silverwood and greatwood.

In addition to using TConstruct's basin, we can use Forestry's Carpenter to combine liquids with a sapling to get the magic saplings.

**Comment by Divineaspect** [comment]
Two gates in the wall of magical wood, sounds good to me.

Third Suggestion: Rare drops from Dryads

**Comment by belathus** [comment]
In order to close this issue, I still need to add the following:
* Generation for menril resin and essence fluid
* Nature-themed dungeons with these items as loot

I'm probably going to create geodes that contain these fluids. Currently, there are already 2 methods of getting these items:
* Pour the right type of fluid on a sapling via a TiC basin (no method to get either fluid, though)
* Rare drop when killing an Ars Magica dryad
