### ISSUE TITLE
Updating to 1.11.2

### ISSUE THREAD

**Issue by belathus** [belathus/Wanderlust-Renewed#72]
Lets use this issue to keep track of which mods have updated to 1.11 that we want to have in this pack.

### Required Mods
- [x] Baubles
- [x] CraftTweaker
- [x] Custom Ore Gen
- [x] Dungeon Tactics
- [x] Enchiridion
- [ ] EnderCore
- [ ] EnderIO
- [x] Immersive Engineering
- [x] IvToolkit
- [x] JEI
- [x] Modtweaker
- [x] PrimalCore
- [X] Recurrent Complex
- [x] Rockhounding
- [x] Roguelike Dungeons
- [x] Tinker's Construct
- [X] Waystones

### Mob Challenge
- [x] BloodMoon
- [x] EnderZoo
- [ ] MobProperties
- [ ] Special AI

### Hunger/Food Challenges Mods
- [x] AppleCore
- [x] AppleSkin
- [x] Cooking For Blockheads
- [x] Pam's Harvestcraft
- [x] Spice of Life

### All Others
- [x] AbyssalCraft
- [x] ActuallyAdditions
- [x] Aroma1997Core
- [x] AromaBackup
- [ ] ArsMagica2
- [ ] AutoRegLib
- [x] Backpack
- [x] Base
- [x] BDLib
- [x] BetterAchievements
- [x] BetterFPS
- [x] BiomesOPlenty
- [x] BloodMagic
- [x] Boatifull
- [ ] Boilerplate
- [x] Botania
- [ ] Charset
- [x] Chisel
- [x] CommonCapabilities
- [x] Controlling
- [x] Cosmetic Armor Reworked
- [ ] Crafting Tweaks
- [x] Custom Main Menu
- [x] Cyberware
- [ ] DaVinci's Vessels
- [x] Deep Resonance
- [ ] Druidry
- [x] ElecCore
- [x] Embers
- [x] Enderthing
- [x] Engineer's Workshop
- [x] Everlasting Abilities
- [x] EvilCraft
- [ ] Expanded Industry
- [x] Extra Alchemy
- [x] Extra Utilities 2
- [x] Fast Leaf Decay
- [x] FoamFix
- [x] Forestry
- [x] Futurepack
- [x] Gendustry
- [x] Giacomo's Fishing Nets
- [ ] Goetia
- [x] Grapple Mod
- [x] Grue
- [ ] Guide API
- [ ] Hard Lib
- [ ] Infinity Lib
- [x] Integrated Dynamics
- [x] Integrated Tunnels
- [ ] Inventory Sorter
- [x] Iron Chests
- [ ] JEI Bees
- [ ] Just Enough Resources
- [x] Level Up!
- [x] LibrarianLib
- [x] LibVulpes
- [ ] LunatrisCore
- [x] Mantle
- [x] McJtyLib
- [ ] MCMultipart
- [x] ModularUtilities
- [ ] MoreBees
- [ ] MoreOverlays
- [x] Morpheus
- [ ] MovingWorld
- [x] MTLib
- [ ] NashornLib
- [x] Natura
- [x] NaturalPledge
- [ ] NetherCore
- [ ] NetherEx
- [ ] NetherMetals
- [x] NetherPortalFix
- [x] NoFOV
- [ ] NomadicTents
- [ ] Ore Flowers
- [x] PersistentBits
- [x] Quark
- [ ] Railcraft
- [ ] Refined Relocation
- [x] Refined Storage
- [ ] Refraction
- [x] Reliquary
- [ ] ResourceLoader
- [x] RFTools
- [x] RFToolsCTRL
- [x] Roots
- [ ] Runes Of Wizardry
- [ ] Signals
- [x] SpartanShields
- [ ] Stackie
- [x] Surge
- [ ] TAIGA
- [x] Tesla
- [x] The One Probe
- [ ] Tinker's Defense
- [ ] Tombstone (or some other gravestone mod)
- [x] TrashSlot
- [x] ViesCraft
- [ ] WIRED

**Comment by Alan19** [comment]
Can we move dungeon tactics and botania to the required section since they're a big part of the loot in Roguelike Dungeons?

**Comment by belathus** [comment]
Done.

**Comment by Alan19** [comment]
Also, Botania and Chisel are somewhat required since their blocks are used a lot in the custom dungeons

**Comment by Divineaspect** [comment]
Customstuff is out for 1.11

**Comment by greenking13** [comment]
There is now Cooking for Blockheads 1.11.2 version.
https://minecraft.curseforge.com/projects/cooking-for-blockheads/files/2381577

**Comment by belathus** [comment]
Well, we updated. We're done with this one.
