### ISSUE TITLE
Re-Add the original recipe for Bark Knife (Roots)

### ISSUE THREAD

**Issue by soulhakr** [belathus/Wanderlust-Renewed#76]
Re-Add the original recipe for Bark Knife (Roots) back as an additional alternate to the simpler (read: more accessible) recipe that's currently there.

**Comment by belathus** [comment]
Roots is pulled. :P

**Comment by Divineaspect** [comment]
Also, you can use the workblades to strip bark from logs.

Jeremiah Grimsley


"All of humanity is in peril of extinction if each one of us does not dare,
now and henceforth, always to tell only the truth, and all the truth, and
to do so promptly — right now." - R Buckminster Fuller
