### ISSUE TITLE
Levelup Rebalance

### ISSUE THREAD

**Issue by Divineaspect** [belathus/Wanderlust-Renewed#79]
1. Point every level
2. Cap skills at 25
3. Bronze Age retrain option.

**Comment by Alan19** [comment]
- [ ] Point every level
- [ ] Cap skills at 25
- [ ] Bronze Age retrain option.

**Comment by Alan19** [comment]
The recipe for the tome of unlearning should be the bronze tools in the corners, 2 lead plates on the top and bottom, a dark gem on the left and right and a book in the center

**Comment by Alan19** [comment]
Closed through bronze and steel age unlearning book recipes
