### ISSUE TITLE
Stone Rods

### ISSUE THREAD

**Issue by Divineaspect** [belathus/Wanderlust-Renewed#8]
As things stand crafting stone rods don't make a lot of sense with primal core etc.
However if we leave them in we could use them instead of iron rods in the primal core lantern which would make that a lot more accessible when you actually need them.

**Comment by belathus** [comment]
Stone rods can also be used in the roots incense brazier, which I just wrote a script for. Backpacks also has a stone stick item that, I'm guessing, is used in the tier 2 backpacks.

**Comment by Divineaspect** [comment]
Is this the two stone stacked rod?

**Comment by belathus** [comment]
It is currently using the stone tool rod from Tinker's Construct. Stacking two cobble or two stone on top of each other does make one of them.

**Comment by Divineaspect** [comment]
...my impulse is to limit this to crafting with smoothstone
