### ISSUE TITLE
New Recipe for Storage Crate Keeper

### ISSUE THREAD

**Issue by Alan19** [belathus/Wanderlust-Renewed#82]
@Divineaspect and I were discussing how the storage crate keeper should be available before the iron age. Any ideas for a new recipe that would make it more accessible? (The storage crate keeper is consumed when the storage crate is moved)

**Comment by belathus** [comment]
Current recipe for the keeper: 4 planks, 4 iron ingots, and a black quartz (actuallyadditions:itemMisc:4).

**Comment by Alan19** [comment]
Closed with bronze age recipe
