### ISSUE TITLE
Possibility to gate Refined Storage

### ISSUE THREAD

**Issue by greenking13** [belathus/Wanderlust-Renewed#87]
As it stands, Refined Storage is an amazing mod for storage, and has it so it is quite easy to automate things in a rapid manner after starting it. If you wanted to gate it, besides changing the recipes for the printed materials, the best and easiest ways would be to either change the recipe of quartz enriched iron or disable a multitude of the various recipes for silicon.
While you could just change the quartz enriched iron to be steel instead of iron, my personal preference would be to disable all methods of silicon except for the way to create it through Rockhounding Chemistry. Because, tbh, the only reason I have used Rockhounding so far is to make the bloomery. It would be an interesting take to start using the chemistry side of the mod as well for various parts.

This does come with the side effect of having a few recipes in Ender IO be a bit more difficult, but not excessively more difficult.

**Comment by belathus** [comment]
Alright, I made the quartz refined iron take steel.

I'll consider changing the recipe for silicon. For now though, I'm going to close this issue. I'll need to get into Refined Storage myself to get a better idea as to how I'd like to change the recipes further.
