### ISSUE TITLE
Abyssalcraft food rebalance, iron chests mod modifications, and chiselled redstone modification

### ISSUE THREAD

**Issue by greenking13** [belathus/Wanderlust-Renewed#89]
~~---Disable the iron plate "abyssalcraft:ironp" It has no purpose besides putting a few foods and plates and is extremely cheaty because it doubles the food and sat of chicken, porkchop, beef, fish, and Abyssalcraft fried egg.
---Disable fried egg "abyssalcraft:friedegg" because of pam's already has one and the AC version is crafted easier.~~
---I remember earlier that you could get blocks of chiselled redstone from a chest and convert them back into blocks of redstone. From chisel.zs script, I've made a rudimentary version of disabling chiselling redstone blocks and added a recipe to them. If wanted, I can toss it onto the issues page of github.
---I can see in storage.zs that you have the creastion of iron chests chests disabled and created through the smeltery. You can use the iron chest upgrades to circumvent this. I can quickly modify storage.zs to account for this, so long as there isn't any current recipes of pouring iron onto wooden planks.

Update: Pull request submitted for the first two issues.

**Comment by belathus** [comment]
Since we removed Abyssalcraft, decided not to go with allowing the chisel blocks to be purely decorative, and no longer have iron chests, I'm gonna close this. I'll do something similar with metal chests, though, but it'll be different than what is here.
