### ISSUE TITLE
Restricting Rotten Flesh into Leather

### ISSUE THREAD

**Issue by Divineaspect** [belathus/Wanderlust-Renewed#9]
Look we all love rotten flesh into leather, but it removes a major challenge, especially in early game.

**Comment by Divineaspect** [comment]
When do we want it to be a thing we allow, or what resource do we want to tie to it?

**Comment by belathus** [comment]
Hm. I don't mind rotten flesh to leather via EvilCraft. Obviously, the method using the drying basin needs to go. What other methods of flesh->leather do we have?

**Comment by belathus** [comment]
Okay, this should no longer be a thing using Integrated Dynamics. We'll have to test it out, though, to be sure.
