### ISSUE TITLE
Dilithium Crystals mod variation

### ISSUE THREAD

**Issue by greenking13** [belathus/Wanderlust-Renewed#90]
The Dilithium Crystal from Tinkers Alloying Addon is oredict with the Dilithium Crystal from Advanced Rocketry (Technically in libVulpes) except that the AR one cannot be smelted in the TiC smeltery. Another note is that I do not know the variation in hardness of the two.

**Comment by belathus** [comment]
TAIGA's dilithium has a mining level of diamond, hardness and resistance of 18, looks like it sheds a small amount of light, drops 3 crystals when mined and gives 10 XP.

LibVulpes' dilithium has a mining level of diamond, default hardness and resistance, and, I'm guessing, drops itself, but can be converted to dust or crystals.

I'm guessing that what I need to do here is disable one or the other and make them compatible with each other via a recipe to convert between the two, make it so you can melt the LibVulpes one in a smeltery, or adding one or the other to the oredictionary.

**Comment by belathus** [comment]
Just FYI, the hardness is the time, in (seconds * 1.5) to mine the block, divided by the tool's speed modifier. The speed modifier for an unenchanted vanilla diamond pickaxe is 8, so the amount of time to mine dilithium is 3.375 seconds with a diamond pickaxe.

The efficiency enchantment adds to a tool's speed. The amount it adds is equal to the enchantment level squared plus one. Thus, efficiency 1 adds 2 to the speed while efficiency 5 adds 26. An efficiency 5 diamond pickaxe would thus take 0.8 seconds to mine TAIGA's dilithium ore.

I'm writing this mostly for my own benefit; don't mind me, I just wanted to know this and was writing it as I was looking it up. It looks like the Tinkers Construct speeds directly reflect the speeds listed here, so a TiC tool will likely be unable to keep up, speedwise, with an Efficiency 5 enchanted tool (diamond's total speed: 34).

**Comment by belathus** [comment]
We're probably going to remove TAIGA, so I'm gonna consider this resolved.
