### ISSUE TITLE
Craft 1 Flint with 2, 3, or 4 gravel

### ISSUE THREAD

**Issue by Divineaspect** [belathus/Wanderlust-Renewed#97]
We should remove two of those options.

**Comment by belathus** [comment]
I removed the 3->1 recipe from Tinker's Construct, and I removed the recipe added by PrimalCore. I'm not sure if that was the 2->1 or the 4->1 recipe, but either way, we should only have one left.

**Comment by belathus** [comment]
Looks like this is fixed. Lance complained about the 2->1 and 3->1 recipes not working (they'll still show up in JEI until we update the client configs). I'm curious what mod adds the 4->1 recipe so I could disable that then add my own. I'm honestly okay with the 2->1 ratio that seems to have been added by PrimalCore.
